### ISSUE TITLE
上周五晚重签后,客户回复还是不行

### ISSUE THREAD

**Issue by bruce107** [g763007297/GQResign#1]
![snip20160829_1](https://cloud.githubusercontent.com/assets/17800060/18039535/91df60ca-6dd6-11e6-8da6-de119a6d9bb1.png)

**Comment by g763007297** [comment]
是用的我这个吗？  还是之前我给你的那个包？

**Comment by bruce107** [comment]
你后面又 resign 的

**Comment by bruce107** [comment]
我自己没用你这个, 早上客户重新给了个 p12和配置文件, 我重新打包, 应该是可以了

**Comment by g763007297** [comment]
那可能是他之前给的证书或者配置文件有问题
