### ISSUE TITLE
感谢分享，同时希望

### ISSUE THREAD

**Issue by Ander456** [g763007297/GQResign#3]
感谢分享，同时希望作者可以简化一哈。。这么长看的头好晕。。然后 关于 脚本中
#提取P12文件中得证书名 这一部分
`    distributionCer=`openssl pkcs12 -password pass:"" -in $p12File -nodes 2>&1|grep friendlyName|head -n 1|sed 's/friendlyName://g'| grep -o "[^ ]\+\( \+[^ ]\+\)*"`
`
在我这貌似我目录下放了一个xx.p12并没有成功 导致 一直 抽取所有本机的证书。。其实我只希望它获取我制定的证书

**Comment by g763007297** [comment]
多谢你的肯定，你所说的简化是指把代码长度简化？
通过p12获取证书只是其中的一种选择，你可以不放p12文件，然后我会读取系统中已有的证书供你选择，直到你选择匹配的证书，如果你选择有错又会重新选择的，所以会存在一直抽取本机的证书。
