### ISSUE TITLE
描述文件与选择的证书是一致，但是签名失败

### ISSUE THREAD

**Issue by huangwenxian** [g763007297/GQResign#5]
我试过好几个证书一直是这样。这是签名的log
/Users/huangwenxian/Desktop/chongqian/workSpace/unzipIpa/Payload/lhh.app/Frameworks/ZQSDK.framework: replacing existing signature
17:29:58.1526030998[执行]/Users/huangwenxian/Desktop/chongqian/workSpace/unzipIpa/Payload/lhh.app/Data/Managed/mono/2.0 签名开始
/Users/huangwenxian/Desktop/chongqian/workSpace/unzipIpa/Payload/lhh.app/Data/Managed/mono/2.0: bundle format unrecognized, invalid, or unsuitable
17:29:58.1526030998[出错]失败原因:签名失败

**Comment by g763007297** [comment]
1）首先查看/usr/bin目录下是否存在codesign_allocate程序，如果存在，执行改名操作。 如果不存在，直接执行第二步
sudo mv /usr/bin/codesign_allocate /usr/bin/codesign_allocate_old
2）将xcode目录下的codesign做一个软链接
sudo ln -s /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/codesign_allocate /usr/bin
